/*
 * medialockerapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 03/03/2017
 */

package apiclient_pkg

import "medialockerapi_lib/models_pkg"

/*
 * Interface for the APICLIENT_IMPL
 */
type APICLIENT interface {
    AddMediaItem (*models_pkg.MediaItem) ([]*models_pkg.MediaItem, error)

    GetLibraryIndex (*int64, *int64) ([]*models_pkg.MediaItem, error)
}

/*
 * Factory for the APICLIENT interaface returning APICLIENT_IMPL
 */
func NewAPICLIENT() APICLIENT {
    return &APICLIENT_IMPL{}
}