/*
 * medialockerapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 03/03/2017
 */

package medialockerapi_lib

/** The base Uri for API calls */
const BASEURI string = "http://example.com/api"

