/*
 * medialockerapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 03/03/2017
 */

package models_pkg


/*
 * Structure for the custom type MediaItem
 */
type MediaItem struct {
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    Title           string          `json:"title" form:"title"` //TODO: Write general description for this field
    Url             *string         `json:"url,omitempty" form:"url,omitempty"` //TODO: Write general description for this field
}
